services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    mem_limit: 4g
    mem_reservation: 2g
    user: root
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:12345@db:5432/postgres
      JWT_SECRET: shabapatotouataksojfsdljfaoieioifhobaojfdoij02390ru2093f0c2n099uweu0f0pq239idj
      NODE_ENV: production
      OFFICE_ID: CRS001328
      FLIGHT_API_USERNAME: api
      FLIGHT_API_PASSWORD: LrW1Y0J)Kv6h
      ZIBAL_MERCHANT_ID: zibal
      NEXT_PUBLIC_APP_URL: http://185.192.113.199:3000
      SMTP_HOST: smtp.mail.yahoo.com
      SMTP_PORT: 587
      SMTP_USER: ahura.alipur19@yahoo.com
      SMTP_PASSWORD: xfjmcitbcvhwznwy
      EMAIL_FROM: "safartoday <ahura.alipur19@yahoo.com>"
      APP_NAME: "safartoday"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./public:/app/public
      - ./prisma:/app/prisma
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

    db:
      image: postgres:18
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=12345
        - POSTGRES_DB=postgres
      volumes:
        - postgres_data:/var/lib/postgresql # CHANGED from /var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 10
        start_period: 30s

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@safartoday.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/misc/ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  pgadmin_data:
